[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#F4F6FB"
secondaryBackgroundColor = "#EEF2F8"
textColor = "#1E293B"

[theme.sidebar]
backgroundColor = "#0F1E3D"
secondaryBackgroundColor = "#cedaee"
textColor = "#E2E8F0"
primaryColor = "#4F91FF"
borderColor = "#18376C"

[server]
maxUploadSize = 50
